namespace COMP003A.Assignment1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("100 Things About Me");
            Console.WriteLine("1. I am 19 years old");
            Console.WriteLine("2. I live in Hanford");
            Console.WriteLine("3. This is my 3rd semester at Lemoore College");
            Console.WriteLine("4. I graduated from Hanford West High School");
            Console.WriteLine("5. I enjoy playing video games");
            Console.WriteLine("6. I enjoy learning about many topics");
            Console.WriteLine("7. I like to learn about general space");
            Console.WriteLine("8. I like to learn about space flight");
            Console.WriteLine("9. I like to learn about history");
            Console.WriteLine("10. I don't like remembering exact dates and names");
            Console.WriteLine("11. I like learning about physics");
            Console.WriteLine("12. I like learning about nuclear science");
            Console.WriteLine("13. I like learning about nuclear reactors/facilities");
            Console.WriteLine("14. I like learning about the medieval period");
            Console.WriteLine("15. I like learning about wars");
            Console.WriteLine("16. I like learning about how technologies develop");
            Console.WriteLine("17. I like learning about medieval martial arts");
            Console.WriteLine("18. I like learning martial arts");
            Console.WriteLine("19. I am about 5 foot 6 inches");
            Console.WriteLine("20. Computers have always been part of my life");
            Console.WriteLine("21. I enjoy practical uses of math");
            Console.WriteLine("22. I enjoy clever uses of math");
            Console.WriteLine("23. I have 2 older sisters");
            Console.WriteLine("24. I'm stingy with money");
            Console.WriteLine("25. I really don't like false dilemmas");
            Console.WriteLine("26. I like to sleep");
            Console.WriteLine("27. I like to listen to music");
            Console.WriteLine("28. I enjoy just about almost all music except country");
            Console.WriteLine("29. I enjoy driving");
            Console.WriteLine("30. I drive a manual");
            Console.WriteLine("31. I drive a Honda Civic");
            Console.WriteLine("32. I enjoy learning about sword techniques");
            Console.WriteLine("33. I enjoy learning about the strengths and weaknesses of historical weapons");
            Console.WriteLine("34. I don't really like anime");
            Console.WriteLine("35. I don't watch too many shows");
            Console.WriteLine("36. I don't watch too many movies");
            Console.WriteLine("37. My favorite band in Avenged Sevenfold");
            Console.WriteLine("38. My favorite genre of music is metal");
            Console.WriteLine("39. I enjoy playing fighting games especially");
            Console.WriteLine("40. I enjoy learning how to learn systems in fighting games");
            Console.WriteLine("41. I like learning musical topics");
            Console.WriteLine("42. I like learning techniques in music");
            Console.WriteLine("43. I don't know how to play any instruments");
            Console.WriteLine("44. I think politics are interesting and important");
            Console.WriteLine("45. I don't like how most people go about when discussing politics");
            Console.WriteLine("46. My favorite fighting game is 2XKO");
            Console.WriteLine("47. My favorite horror game is The Outlast Trials");
            Console.WriteLine("48. My favorite PvP game is Chivalry 2");
            Console.WriteLine("49. I don't enjoy the battle royale genre");
            Console.WriteLine("50. I don't enjoy most of the extraction shooter genre");
            Console.WriteLine("51. My favorite number is 12");
            Console.WriteLine("52. My favorite color is green");
            Console.WriteLine("53. I prefer cats over dogs");
            Console.WriteLine("54. My favorite dinosaur is the ankylosaurus");
            Console.WriteLine("55. I like reptiles");
            Console.WriteLine("56. I have 2 cats");
            Console.WriteLine("57. I have 1 dog");
            Console.WriteLine("58. I have 1 snake");
            Console.WriteLine("59. I have a hard time falling asleep");
            Console.WriteLine("60. I have a hard time staying focused while reading");
            Console.WriteLine("61. I have a weak stomach");
            Console.WriteLine("62. I'm fascinated with animals that have especially unique traits, like turtles");
            Console.WriteLine("63. I enjoy reading until I lose focus");
            Console.WriteLine("64. I don't like TikTok");
            Console.WriteLine("65. I don't use TikTok");
            Console.WriteLine("66. I like learning about psychology");
            Console.WriteLine("67. I'm not a fan with how AI has been developing recently");
            Console.WriteLine("68. I don't like partisanship");
            Console.WriteLine("69. I don't like extreme brand loyalty");
            Console.WriteLine("70. I'm not a big fan of shows focused on drama");
            Console.WriteLine("71. I don't care much about shoes");
            Console.WriteLine("72. I look mostly for comfort in clothes");
            Console.WriteLine("73. Winter is my favorite season");
            Console.WriteLine("74. I prefer being cold over being hot");
            Console.WriteLine("75. I don't play sports");
            Console.WriteLine("76. I don't watch sports often");
            Console.WriteLine("77. My favorite sport is basketball");
            Console.WriteLine("78. I don't care for sports teams all that much");
            Console.WriteLine("79. I enjoy hiking");
            Console.WriteLine("80. I enjoy camping");
            Console.WriteLine("81. I enjoy puzzles");
            Console.WriteLine("82. I enjoy optical illusions");
            Console.WriteLine("83. I like weird geometry and problems involving it");
            Console.WriteLine("84. I like to learn about historical figures");
            Console.WriteLine("85. I like challenges");
            Console.WriteLine("86. I learn best by doing");
            Console.WriteLine("87. I like creating theory-crafting solutions");
            Console.WriteLine("88. I likegames that try to be different");
            Console.WriteLine("89. I find it hard to put all my attention into one thing at once over a long period of time");
            Console.WriteLine("90. I enjoy parkour");
            Console.WriteLine("91. I'm a heavy sleeper");
            Console.WriteLine("92. I'm fascinated by art created in unorthodox ways");
            Console.WriteLine("93. I find language interesting");
            Console.WriteLine("94. My favorite type of sweet is chocolate");
            Console.WriteLine("95. I think the Central Valley is an interesting place");
            Console.WriteLine("96. I've liked cooking for the little time I've done it for");
            Console.WriteLine("97. I've recently played Hunt: Showdown");
            Console.WriteLine("98. I like the mnajority of the blue to green spectrum of colors");
            Console.WriteLine("99. I enjoy chemistry");
            Console.WriteLine("100. I've listed 99 items before this one");

        }
    }
}
